random sid on fresh install

diff --git a/vagrantsetup b/vagrantsetup
--- a/vagrantsetup
+++ b/vagrantsetup
@@ -1,4 +1,4 @@
-#!bin/bash
+#!/bin/bash
 
 function installWP {
 	echo "::: INSTALLING WORDPRESS :::"
@@ -9,11 +9,19 @@ function installWP {
   		exit 1
 	fi
 	
+	salts="`wget -qO- https://api.wordpress.org/secret-key/1.1/salt/`"
+	if [[ "$?" != "0" ]]
+	then
+  		echo "an error happened getting random salts!"
+  		exit 1
+	fi
+	
 	tar xf ./wp.tgz
 	mv ./wordpress/* .
 	rmdir ./wordpress
 	rm ./wp.tgz
-	cat ./templates/wp-config.php | sed -e "s/\${db_name}/$1/" -e "s/\${project_name}/$1/" > ./wp-config.php
+	cat ./templates/wp-config.php | sed -e "s/\${db_name}/$1/" -e "s/\${project_name}/$1/" | sed  '45d' | sed "45i $(echo $salts | sed -e 's/[\/&]/\\&/g')" > ./wp-config.php
+	 
 }
 
 function installEdenticBaseTheme {
